image:
  name: $NODE_IMAGE
  entrypoint: ['']

include: 'http://gitlab-service.mt.ec2-internal/public-group/gitlab-shared-pipelines/raw/master/gitlab-npm-publish-job.yml'

stages:
  - install
  - publish

install:
  stage: install
  script:
      - npm install
  cache:
    paths:
        - node_modules/
  only:
      - master